### ISSUE TITLE
Open PR for write up Privilege Escalation I (AppArmor)

### ISSUE THREAD

**Issue by atoamaeto** [atoamaeto/attackdefenseserieslab#1]
Open PR for write up Privilege Escalation I (AppArmor)

**Comment by ilosaurus** [comment]
Oke, pls can u explain detail attack defense lab series?

**Comment by atoamaeto** [comment]
Lab Attack Defense - [Privilege Escalation I AppArmor](https://attackdefense.com/challengedetails?cid=1836)

**Comment by ilosaurus** [comment]
Oke Noted, tq.

**Comment by atoamaeto** [comment]
Oke , review on progress. Thanks

**Comment by atoamaeto** [comment]
Thanks @ilosaurus !
